### ISSUE TITLE
FOSS Version precompiled for Android

### ISSUE THREAD

**Issue by SonicGamerEpisode55** [adil192/ricochlime#15]
Prebuilts on F-Droid with no ads.

**Comment by adil192** [comment]
If you're asking for Ricochlime to be published to F-Droid, you can see the app inclusion request here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13748

**Comment by SonicGamerEpisode55** [comment]
I tried installing the apks and it shows App not installed, because it looks like an broken app package (or sort of this)

**Comment by adil192** [comment]
Did you get the apks from the fdroiddata MR or from this repo's actions?
Also what Android version are you running?

**Comment by adil192** [comment]
Just tried the apks from the MR and I'm hitting the same error. Maybe it's because they're unsigned?

**Comment by SonicGamerEpisode55** [comment]
So where are working foss apks?

**Comment by adil192** [comment]
Nowhere yet

**Comment by adil192** [comment]
You can download the foss APK here: https://github.com/adil192/ricochlime/actions/runs/6300208851

Note that since the signatures are different, you'll want to uninstall and reinstall it through F-Droid when it gets published

**Comment by SonicGamerEpisode55** [comment]
Thanks
