### ISSUE TITLE
Quickly boring

### ISSUE THREAD

**Issue by Cwpute** [adil192/ricochlime#20]
The game is fun for a few rounds, but quickly gets boring… Here is a bunch of vague ideas you might want to play with:

* More content: bigger slimes, slimes with different shapes which bounce off balls in other directions, special bullets, special terrain etc…
* More difficulty: obstacles that move between throws, slimes that are protected on some of their sides…
* More player input: add one-time use items before each throw or during a throw, allow to slightly alter the bullet's course once launched…

**Comment by adil192** [comment]
Ricochlime is actually intended to be repetitive. I get that this only works for some people but I don't intend to increase the complexity any further

**Comment by AeliusSaionji** [comment]
The higher waves (100+) demand you think more carefully about your next and future moves. The repetition exists for me early on as it can take time to get back to the more challenging higher waves.

Which makes it not unlike Suika Game, 2048, etc.

But I wouldnt mind a "drop me in a randomly generated wave 100" option.
