### ISSUE TITLE
(Almost) exponential game speed

### ISSUE THREAD

**Issue by Cwpute** [adil192/ricochlime#22]
Game speed increases by 0.5 times every time you tap the screen. I'd suggest increating that time by bigger factors once you hit 2.0 times speed.
Then increase by 1.0 times, then 2.0 times etc…

**Comment by adil192** [comment]
Higher speeds aren't really needed, and personally I find it fun to spam tap the screen

**Comment by AeliusSaionji** [comment]
I agree with cwpute here. I often want to move faster, but not so fast that I can't see what's happening. Spamming the screen often overshoots my desired speed.
