### ISSUE TITLE
Game Over Bypass

### ISSUE THREAD

**Issue by ztychr** [adil192/ricochlime#26]
Hi @adil192.

First of all, thank you for a great FOSS Android game. 

I noticed a bug in v1.1.0 where if you close the game after reaching the GAME OVER-screen, you will be able to replay your last shot when reopening it. This permits the user to have unlimited retries.

Not really a big deal unless you plan to implement global scoreboard :-)

**Comment by ztychr** [comment]
Woops. Fat fingers.

**Comment by adil192** [comment]
Honestly, I'm comfortable leaving this as-is. There are many ways to retry a round that I've intentionally implemented anyway :)

**Comment by ztychr** [comment]
Cheers. I'll go hunt the rest - thank you for a fun game!
