### ISSUE TITLE
bug: "Restart game" doesn't work after game over then going home

### ISSUE THREAD

**Issue by itsLameni** [adil192/ricochlime#28]
how the bug appeared:
1. lose in the game
2. pressed "<- Home"
3. on the main page of the game i'm clicking on the button "Play"
4. the game tells me again that i'm "game over" and offers to restart the game

i press on the restart button, but nothing happens.

video: https://filetransfer.io/data-package/GyLgIFgM#link

game version: 1.1.0, f-droid
device: realme 10, android 12

**Comment by adil192** [comment]
Thanks! I encountered this bug myself but wasn't able to reproduce it until this
