### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [adil192/ricochlime#29]
https://monitor.f-droid.org/builds/log/com.adilhanney.ricochlime/1010201#site-footer

Could you please take a look? Thanks!

**Comment by adil192** [comment]
Sorry about this, I forgot to add the dummy `AdState.rewardedAdsSupported` getter in the FOSS patch: https://github.com/adil192/ricochlime/commit/994692dcb0fff1fbe6ba5a9afca5cfc79ff08fbd

I was just going to leave it until the next release but I can submit an fdroiddata MR for that commit if that's preferable?

**Comment by licaon-kter** [comment]
can we reopen this?

https://gitlab.com/fdroid/fdroiddata/-/jobs/6433571824#L1683

**Comment by adil192** [comment]
Looks like it's been fixed with fb0c70e0f721c2bd8f227ac89dc487b5328d56d5
