### ISSUE TITLE
Power-ups?

### ISSUE THREAD

**Issue by RustoMCSpit** [adil192/ricochlime#33]
Maybe have blue tree things that give power-ups? I'd recommend looking through RPGs like the Binding of Isaac, Vampire Survivor, and Noita for power-up ideas?

**Comment by RustoMCSpit** [comment]
There should be temporary 1-3 move ones, permanent until loss ones, and item based ones that are temporary

e.g. freeze time for one move. all shots now do fire damage, drink this potion and cut every creature's health in half (one use only)

**Comment by adil192** [comment]
Sorry, I'd like to keep this game simple and minimalistic. I don't want to add any further complexity.

Same with #34, #35, #36, #37, #38.

**Comment by RustoMCSpit** [comment]
> Sorry, I'd like to keep this game simple and minimalistic. I don't want to add any further complexity.
> 
> Same with #34, #35, #36, #37, #38.
> 
> Edit: Looking through these feature request, they're some pretty good ideas. If you ever fork this game or make your own, let me know!

probably wont, if you ever change your mind feel free to add them
