### ISSUE TITLE
F-Droid Release Suggestions

### ISSUE THREAD

**Issue by MonkeyMatrix** [adil192/ricochlime#39]
I was looking at the new update on F-Droid and saw two images containing information about ads. I was unable to find the ad content in the F-Droid release (and I am guessing that it will not be added), so I would suggest removing those two images or modifying them by showing an F-Droid release build which does not contain this content. In addition, I thought it may be helpful to add an F-Droid banner to the README which links to that [page](https://f-droid.org/en/packages/com.adilhanney.ricochlime/). I appreciate your work on this game!

![image](https://github.com/adil192/ricochlime/assets/144576457/4628d625-9e3f-4027-aafa-e5a7a3c4b93d)
![image](https://github.com/adil192/ricochlime/assets/144576457/b30e7d2c-773f-4677-9cc1-2e71b4388bef)

**Comment by adil192** [comment]
Thanks!
