### ISSUE TITLE
1.3.0/F-droid: A step backwards

### ISSUE THREAD

**Issue by Sapiosenses** [adil192/ricochlime#41]
I've been using 1.1.3 for months now and have been very happy with it.

Updated to 1.3.0 today and discovered that both the game play and UI were much more sluggish than 1.1.3, even with the original "fuzzy" typeface.

Not only that, the feature that allows you to restart a game by closing the app and reopening was eliminated, despite the fact that when asked about it here in December you said you wanted to keep it. I use that feature a lot to try to figure out how to come up with a finely tuned strategy to beat a very difficult level, and it makes the game much more addictive as I can oftentimes eventually find the "trick" that completes the level and that feels very satisfying to me.

So I tried to downgrade the app. (I know the latest Android versions are blocking that now but this device is only on Android 10 and that was never changed in that respect) Latest official F-droid app tries to prevent that too but you can still manually select a version. Which didn't work. Tried some other methods including a special "downgrader" tool. Didn't work either.

So I was forced to completely uninstall it, install 1.1.3 again, and now of course my high score is erased.

What a bummer.

I appreciate your efforts on this as it is one of the very few FOSS games I actually spend a significant amount of time playing. I hope you can figure out a way to make the UI/graphics work better in your subsequent versions.

**Comment by adil192** [comment]
The UI font shouldn't change performance at all. But I'll see if I can make an option in settings for the transition duration

**Comment by adil192** [comment]
Closed with 51f61f817c0631b3b61bcb0a8f74374df5938934
