### ISSUE TITLE
Unable to Uninstall due to an unknown error

### ISSUE THREAD

**Issue by TacticalLaptopBag** [adil192/ricochlime#44]
I haven't played Ricochlime in a long time and went to uninstall the app. Trying to do this through my phone's own Package Installer just makes it crash. Trying to do this from F-Droid just shows a toast saying, "Failed to uninstall due to an unknown error" (or just shows "uninstalling" indefinitely)

I'm on a Samsung Note 20 Ultra with latest updates on Android 13. I have not rooted the device.

Note: Other apps uninstall just fine. This one won't even show the prompt of "Are you sure you want to uninstall?" before crashing Package Installer

**Comment by adil192** [comment]
This is an issue with your device that I can't help you with

**Comment by Angelos456** [comment]
i have the exact same issue on my A51, it's the app not the phone.

**Comment by adil192** [comment]
From #72, this looks like an issue with Samsung's Android 13 package installer.
For now, the only solution I have for you is using adb (`adb uninstall com.adilhanney.ricochlime`).
