### ISSUE TITLE
blank screen on Windows

### ISSUE THREAD

**Issue by jerry-ne** [adil192/ricochlime#45]
Today I pick v1.8.1 Win installer, install it for only me. 
It works, until first reboot. Currently I have blank gray screen window on my Win 10.
Reinstall app does not fix it. I also try uninstall and install for all users. Also does not fix it.
Removing json file in `Appdata\Roaming\Adil Hanney\Ricochlime\` also does not fix it.

Any suggestion?

**Comment by adil192** [comment]
Please can you run it in a terminal and let me know the output?
(Let me know if you want more detailed instructions)

**Comment by jerry-ne** [comment]
Yes, It works. Thanks!
