### ISSUE TITLE
Erratic physics on high speed

### ISSUE THREAD

**Issue by je-sendra** [adil192/ricochlime#47]
When increasing the speed to high limits (maybe like 8x) the game physics start acting erratically.

This can be clearly seen in the video in the part where the balls start going down without touching anything (at around 12x speed).

The easiest solution would be to implement a speed limit.

I am able to fix this myself somewhen around next week.

This has been tested on Android.

https://github.com/adil192/ricochlime/assets/115565209/0960bec5-f12f-428e-9eae-2c54fd13c21c

**Comment by adil192** [comment]
This is intentional to stop balls getting stuck going horizontal. It'll happen regardless of speed.
